rest:
  auth-open: false #jwt鉴权机制是否开启(true或者false)
  sign-open: false #签名机制是否开启(true或false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key
  ignore-URI: /auth,/user/register,/user/logout,/film/getFilms,/film/films,/film/getIndex,/film/getConditionList,/cinema/getFields,/cinema/getFieldInfo,/cinema/getCinemas,/cinema/getCondition,/cinema/isTrue,promo/publishPromoStock,promo/getPromo

server:
  port: 8088 #项目端口

mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/rest/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.rest.common.persistence.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

spring:
  application:
    name: guns-gateway
  dubbo:
#    registry: zookeeper://127.0.0.1:2181
    registry: zookeeper://106.14.140.211:2181
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/guns_rest?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 123456
      filters: log4j,wall,mergeStat
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
#    host: localhost
    host: 106.14.140.211
logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: guns-gateway.log

meeting:
  film:
#    preImg: http://img.meetingshop.cn/
    preImg: https://da4j-1300799324.cos.ap-shanghai.myqcloud.com/
